### ISSUE TITLE
KeepAlive pings are always sent at 30secs

### ISSUE THREAD

**Issue by Abhijith-net** [emqx/CocoaMQTT#265]
KeepAlive pings are always sent at 30secs. Connection options are NOT honored.

Kindly check.

**Comment by HJianBo** [comment]
Hi, @Abhijith-net I have checked the implement for keepalive mechanism. the ping interval actually is equal to `(keepAlive / 2) + 1`:

https://github.com/emqtt/CocoaMQTT/blob/114b368aeccf9926b689a67a1be379b424f06bb9/Source/CocoaMQTT.swift#L533-L542

**Comment by HJianBo** [comment]
It is a so weird implement. I'll change it to the real keepAlive value.

**Comment by Abhijith-net** [comment]
@CrazyWisdom Whats the ETA for the fix?

**Comment by Abhijith-net** [comment]
@CrazyWisdom Could you pls help fix this?

**Comment by CrazyWisdom** [comment]
> @CrazyWisdom Whats the ETA for the fix?

We will release v1.2.3 by tomorrow.

**Comment by HJianBo** [comment]
Hi, guys!  I have released it at 1.2.4 version.

Please check it.
