### ISSUE TITLE
Loop forever when sending Qos1/Qos2 message.

### ISSUE THREAD

**Issue by wickyou23** [emqx/CocoaMQTT#277]
Hi guys,

I checked the FW(v1.2.3). I think I found some issue here. Please check the code below:

<img width="748" alt="Screen Shot 2019-06-18 at 8 02 40 PM" src="https://user-images.githubusercontent.com/5183190/59684428-30565700-9204-11e9-8fa5-dde0921780ff.png">

It was a loop forever when sending Qos1/Qos2 message although It sent successfully. I think CocoaMQTTTimer will keep "frame" instance, then resend. Should get "frame" instance from the inflight queue?

**Comment by HJianBo** [comment]
Yes, it is a very ugly bug... 😂

I'll fix it now

**Comment by HJianBo** [comment]
Hi, @wickyou23 I have submit a draft RP to fix this problem. Please review it or give some comment for it if it possible

Thanks :)

**Comment by wickyou23** [comment]
> Hi, @wickyou23 I have draft a RP to fix this problem. Please review it or give some comments for it if it possible
> 
> Thanks :)

Hi, @HJianBo I reviewing this issue, which you fixed. Currently, It works well. If I see it again I will raise it to you. Thank for your support.

**Comment by HJianBo** [comment]
Hi, @wickyou23 I have released it at 1.2.4
