### ISSUE TITLE
Auto reconnect retry time interval

### ISSUE THREAD

**Issue by sachinvas** [emqx/CocoaMQTT#286]
@emqx, We were trying this awesome open source implementation of MQTT. This is one of the best framework we came across, thank you so much for for making it open source.

Right now the auto reconnect retry time interval is fixed and the client always use the same interval for reconnection.

However, it should have been exponential (lets say from 2 seconds) up-to maximum interval (lets say 128 seconds) and it should stay at the maximum interval (128 seconds) if all the retry fails. This way it would save the battery.

1. Is there anyone currently working on providing this solution?
2. Can we contribute if no one is working on this?

**Comment by HJianBo** [comment]
A Pretty Suggestion!! Thanks  @sachinvas :)  

Take easy there, you can open a PR to implement it. We are very grateful to someone who can submit PR to optimize the functionality of this library.

If your time is not allowed, we will fix it later

**Comment by sachinvas** [comment]
Hi @HJianBo, Thank you for the confirmation. I will be implementing and creating a PR soon.

**Comment by Abhijith-net** [comment]
> Hi @HJianBo, Thank you for the confirmation. I will be implementing and creating a PR soon.

Thanks @sachinvas much needed change!

**Comment by sachinvas** [comment]
Hi @HJianBo, I have raised a Pull Request for the enhancement. Please review and merge.

**Comment by HJianBo** [comment]
Hi, @sachinvas Thanks for you contributed PR. I have released these changes at 1.2.5

And, Are you interested in joining us to make this library better? I have sent an invitation to you:

https://github.com/emqx/CocoaMQTT/invitations

If you are interested, we can maintain and develop new versions together. 😁

**Comment by sachinvas** [comment]
Hi @HJianBo, Thank you for the invite. Sure, I am interested in contributing to the Open Source Projects.

Thank you for the invite and I have already accepted it.

**Comment by HJianBo** [comment]
Haha Welcome to join CocoaMQTT.

---

Close the issue first, About the private queue for timer, we can open a new PR or issue to discuss it
