### ISSUE TITLE
Crash MQTTReader frameReady

### ISSUE THREAD

**Issue by adicatur** [emqx/CocoaMQTT#288]
Hi there, 

I'm using CocoaMqtt `1.2.4` version, and get this issue, and the number of the crash quite high. 

<img width="1056" alt="Screen Shot 2019-07-19 at 10 24 26" src="https://user-images.githubusercontent.com/10487211/61507774-4e84c200-aa11-11e9-9371-46d85b365a9e.png">

Could you please check this issue?

Regards

**Comment by adicatur** [comment]
Hi @HJianBo  I've created PR for this could you please check, https://github.com/emqx/CocoaMQTT/pull/291. Thanks

**Comment by HJianBo** [comment]
Yes, it has been fixed and released at 1.2.5. Thanks for your contribution 👍
