### ISSUE TITLE
error: index out of range

### ISSUE THREAD

**Issue by ioschen** [emqx/CocoaMQTT#296]
<img width="992" alt="WechatIMG5" src="https://user-images.githubusercontent.com/5210832/63998416-a09e2480-cb33-11e9-8ac0-deb1ea91a66b.png">

**Comment by Y2JChamp** [comment]
i have experienced this bug too at this line:
                inflight[idx] = duplicatedFrame
In my case idx = 0 at that point

**Comment by HJianBo** [comment]
Hi guys, It has been fixed at v1.3.0-rc.1. Thanks for your attention
