### ISSUE TITLE
MQTT does not connect at all, always disconnects.

### ISSUE THREAD

**Issue by shezu** [emqx/CocoaMQTT#301]
I have been trying to connect mqtt to my mqtt Server using 3.1, but i am unable to do so. here is my code :
i am using Cocoa MQTT for this:

```swift
mqtt = CocoaMQTT(clientID: clientId, host: server, port: UInt16(port))
     //   mqtt.cleanSession = true
        mqtt.username = ""
        mqtt.password = password
//        mqtt.willMessage = CocoaMQTTWill(topic: "/will", message: "dieout")
        let driverID = UtilityHelper.getUserId()
        mqtt.keepAlive = 60
        self.mqtt.delegate = self
        
       
        mqtt.connect()
```

**Comment by Faizanali-matechco** [comment]
facing exactly same issue, and none of the solution is working already stated on STOverFlow.

**Comment by MurtazaMatechCO** [comment]
Facing the same issue.

**Comment by D3rP4nd4** [comment]
Same here, i keep getting stuck in the connecting phase

**Comment by HJianBo** [comment]
Hi, guys Which the CocoaMQTT version, MQTT services name, and version used?

After occurred this problem, you can turn on the debug log by:
```
mqtt.logLevel = .debug
```

**Comment by MurtazaMatechCO** [comment]
@HJianBo After setting log level it only prints connect to ip in console but delegates not called

**Comment by HJianBo** [comment]
@MurtazaMatechCO  Could you paste the detail log lines? and CocoaMQTT version

And, the CocoaMQTT works on the Main queue by default, so plz make sure the App did not block it.

**Comment by MurtazaMatechCO** [comment]
@HJianBo I am using version 1.2.4, It logs these lines
CocoaMQTT(info): Connected to 18.194.27.95 : 8000
CocoaMQTT(debug): Socket write message with tag: 0

and then call disconnected delegate.

**Comment by HJianBo** [comment]
@MurtazaMatechCO It seems the MQTT broker disconnects it by voluntary. Maybe you can check the server logs what happened after receiving the CONNECT request.

In addition, the 1.2.x  version has a BUG at assembling CONNECT request for 'Will Message'. It will send an invalid CONNECT frame to broker. So this mistake can also lead to this phenomenon

**Comment by MurtazaMatechCO** [comment]
@HJianBo It always give me this error, I've tried with different servers but still same issue. Only State change and disconnects delegates called. Other delegates never get called.

**Comment by shezu** [comment]
GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer"
over and over again the same stupid error. Does MQTT even work ???

**Comment by HJianBo** [comment]
@shezu 

> GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer"
over and over again the same stupid error. Does MQTT even work ???

These logs just show that the broker closes the socket connection for some reason.

So, Plz tell me the CocoaMQTT version and Broker name, version to help me reproduce it

**Comment by shezu** [comment]
CocoaMQTT version : 1.3.0-alpha.1
Broker name : broker.mqttdashboard.com

**Comment by shezu** [comment]
this is the whole debug response : 
new state: connecting
CocoaMQTT(info): Connected to 18.185.216.165 : 8000
CocoaMQTT(info): Enable backgrounding socket successfully
CocoaMQTT(debug): SEND: FrameConnect(fixedHeader: 16, PROTOCOL_LEVEL: 4, PROTOCOL_VERSION: "MQTT/3.1.1", PROTOCOL_MAGIC: "MQTT", clientID: "clientId-7MlE6C7bMp", keepalive: 60, willMsg: nil, username: Optional(""), password: Optional(""), cleansess: true)
[TRACE] [didStateChangeTo]: new state: disconnected
[TRACE] [didDisconect]: Error Domain=GCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}

**Comment by HJianBo** [comment]
I guess the `18.185.216.165:8000` is not available services? I can't connect to it with other MQTT Client:
```
mosquitto_sub -h 18.185.216.165 -p 8000 -t test -i clientId-7MlE6C7bMp -d
```

**Comment by shezu** [comment]
it is online, it is a test mqtt server.
http://www.hivemq.com/demos/websocket-client/

**Comment by HJianBo** [comment]
See: http://www.mqtt-dashboard.com

You should use `broker.hivemq.com:1883`  address instead of `broker.mqttdashboard.com:8000`

The latter address is based on Websocket not TCP.  CocoaMQTT is supported TCP over only

**Comment by shezu** [comment]
ohkay,, so how can i connect to a Websocket ?
By the Way thank you so much!

**Comment by HJianBo** [comment]
Sorry, I don't find a repository to support Websocket with Swift.

Maybe CocoaMQTT will support Webscoket connection, but that will definitely be many versions later

**Comment by shezu** [comment]
ohkay,, thanks a lot for your help mate !
