### ISSUE TITLE
How to publish data type message?

### ISSUE THREAD

**Issue by skytodmoon** [emqx/CocoaMQTT#303]
In some case , we need convert dict/array to data and publish?
can support these cases?

add:sometimes we need to publish audio data by mqtt. Can it support data or bytes?
Oh,great I find the method : publich(cocoaMessage) can resolve this problem.
@HJianBo

**Comment by HJianBo** [comment]
Hi @skytodmoon, You should convert the dict/array to serialized format data with others framework

**Comment by skytodmoon** [comment]
publich(CocoaMessage) can resolve this problem. Close this . Greate mqtt lib.
