### ISSUE TITLE
Can't get empty publish message-1.3.0-1

### ISSUE THREAD

**Issue by skytodmoon** [emqx/CocoaMQTT#312]
When some device send me an empty publish message,I can not get it. After i detect it in the error stack I found the pos of FramePublish.swift is wrong is this data: end is 61 ,pos is 62,but the data.bytes.length == 62,the pos is out of bounds.

> [0, 60, 47, 114, 101, 109, 111, 116, 101, 97, 112, 112, 47, 109, 111, 98, 105, 108, 101, 47, 98, 114, 111, 97, 100, 99, 97, 115, 116, 47, 112, 108, 97, 116, 102, 111, 114, 109, 95, 115, 101, 114, 118, 105, 99, 101, 47, 97, 99, 116, 105, 111, 110, 115, 47, 116, 118, 115, 108, 101, 101, 112]

`        // payload
        let end = bytes.count - 1
        
        if (end - pos >= 0) {
            _payload = [UInt8](bytes[pos...end])
            // receives an empty message
        } else {
            return nil
        }`

**Comment by skytodmoon** [comment]
@HJianBo  please see the problem above, thank you!

**Comment by HJianBo** [comment]
It will be fixed at v1.3.0, Thanks for your feedback

**Comment by skytodmoon** [comment]
Temporary modification：comment the return nil
`        // payload
        let end = bytes.count - 1
        
        if (end - pos >= 0) {
            _payload = [UInt8](bytes[pos...end])
            // receives an empty message
        } else {
            //return ""
        }`

**Comment by HJianBo** [comment]
I have fixed at develop branch, you can see
https://github.com/emqx/CocoaMQTT/commit/4fa300cd1f696fc82fdf5e80f87231fa20a0d805

**Comment by HJianBo** [comment]
Hi @skytodmoon It has released at v1.3.0-rc.1. Thanks for your contribution
