### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by camelliacafe** [emqx/CocoaMQTT#327]
Dear,

When update Xcode,

Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2 compiler

Best regards!

**Comment by cyrusingraham** [comment]
Not much info to go on here but it is likely this is an issue locally to your computer and not an issue with the library. What are you using as a dependency manager? Carthage? If so, you need to recompile your local builds using the Swift 5.2 compiler which was probably part of the Xcode update. Simply running `carthage bootstrap` should fix things for you.

**Comment by camelliacafe** [comment]
Thank you for your kindly reply. However, it still does not work.
Do you success in  Xcode 11.4?
Thanks a lot!

carthage update

*** Building scheme "CocoaMQTT" in CocoaMQTT.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/camellia/Documents/iphone\ Remote/IoT20191201/CamelliaIoT/Carthage/Checkouts/CocoaMQTT/CocoaMQTT.xcodeproj -scheme CocoaMQTT -configuration Release -derivedDataPath /Users/camellia/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/CocoaMQTT/1077744b9e2e8d16e6551ce0e87fa883c788556e -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/7d/_d1l_t7d1870clm7vx0ghthr0000gn/T/CocoaMQTT SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/camellia/Documents/iphone Remote/IoT20191201/CamelliaIoT/Carthage/Checkouts/CocoaMQTT)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/7d/_d1l_t7d1870clm7vx0ghthr0000gn/T/carthage-xcodebuild.KdJMtM.log

**Comment by efdalustaoglu** [comment]
Same issue here, after calling `carthage bootstrap` with xcode 11.4.1.

**Comment by john-doe1337** [comment]
This helped me.

Project Settings -> Build Settings:
Build Libraries for Distribution = YES

https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler

**Comment by nok6583** [comment]
Same issue here, after calling carthage bootstrap with xCode 11.4.1.

**Comment by camelliacafe** [comment]
carthage update
for Xcode 11.5, everything is ok!
Thanks for all.
