### ISSUE TITLE
Getting intermittent "Operation timed out" 

### ISSUE THREAD

**Issue by basilmariano** [emqx/CocoaMQTT#367]
This error is thrown in `func mqttDidDisconnect(_ mqtt: CocoaMQTT, withError err: Error?)`
It not really descriptive so i don't know what really the issue there.

**Comment by leeway1208** [comment]
MQTT V5.0 can fix this issue. Now we have the V5.0 test version on branch dev/2.0.

**Comment by basilmariano** [comment]
Closing this issue as there is already 2.0 version
