### ISSUE TITLE
Xcode 13 - 'FoundationConnection' is inaccessible due to 'internal' protection level'

### ISSUE THREAD

**Issue by LucaKaufmann** [emqx/CocoaMQTT#393]
On the latest master version, Xcode 13 throws the error 'FoundationConnection' is inaccessible due to 'internal' protection level'.  Does the FoundationConnection have to be marked as public as well?
``` swift
public enum CocoaMQTTError: Error {
    @available(OSX 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *)
    **enum FoundationConnection: Error {**
        case closed(URLSessionWebSocketTask.CloseCode)
    }

    case invalidURL
    case readTimeout
    case writeTimeout
}
```

**Comment by leeway1208** [comment]
My Xcode 13 does not throw the error you showed. I downloaded project  and tested suessfully. But FoundationConnection be marked as public also runs well too.   :)

**Comment by leeway1208** [comment]
Hi , My Xcode 13 does not throw the error you showed. I downloaded project and tested successfully. But FoundationConnection be marked as public also runs well too. :)

**Comment by hoangtung31** [comment]
I have the same issue as @LucaKaufmann

**Comment by LucaKaufmann** [comment]
I opened PR #396 that should fix this

**Comment by LucaKaufmann** [comment]
PR was merged into master 👍
