### ISSUE TITLE
Crash on FrameUnsubscribe, reading description

### ISSUE THREAD

**Issue by NicoDB79** [emqx/CocoaMQTT#414]
Hi, I'm facing this issue when reading description property of FrameUnsubscribe. topicFilters is nil and it is forced unwrapped.
Anyone find the same issue?
I'm using CocoaMQTT v2.0.0 and MQTT v3.1.1

![Schermata 2021-11-16 alle 12 59 45](https://user-images.githubusercontent.com/28931977/141981693-6539af57-a21e-412a-a531-fe11626bf7db.png)

**Comment by leeway1208** [comment]
@NicoDB79 hi, I will fix it asap.

**Comment by NicoDB79** [comment]
> @NicoDB79 hi, I will fix it asap.

Thank you
