### ISSUE TITLE
Subscription Ack is not getting Called in CocoaMQTTDelegate

### ISSUE THREAD

**Issue by rajeevradhakrish** [emqx/CocoaMQTT#420]
The following warning is coming from the MQTT library in subscription Ack and the delegate is not getting called.
CocoaMQTT(warning): UNEXPECT SUBACK Recivied: SUBACK(id: 1)

The following code inside the library return with wear .  I have tested with many brokers but still getting the same warning and ack fails.

guard topicsAndQos.count == suback.grantedQos.count else {
            printWarning("UNEXPECT SUBACK Recivied: \(suback)")
            return
        }

**Comment by leeway1208** [comment]
@rajeevradhakrish  Thanks for your report. I will check it.

**Comment by JGVB** [comment]
getting 
CocoaMQTT(warning): UNEXPECT SUBACK Recivied: SUBACK(id: 1)  **id 1-10

Does this cause any functional problems? Or is truly just a warning?

**Comment by leeway1208** [comment]
@JGVB perhaps is our mistake. The newest version fix the subback frame problem.😄

**Comment by tomerpetel** [comment]
Any possibility this still occurs on 2.0.2?

I'm on 2.0.2 according to the Podfile.lock:
...
 - CocoaMQTT (2.0.2):
    - CocoaMQTT/Core (= 2.0.2)
  - CocoaMQTT/Core (2.0.2):
    - CocoaAsyncSocket (~> 7.6.5)
...

And still encountering this bug. It looks like the topics count and ack count are not the same. I'm failing here:

` guard topicsAndQos.count == suback.grantedQos.count else {
            printWarning("UNEXPECT SUBACK Recivied: \(suback)")
            return
        }`

I tried to subscribe to one topic only and still seeing the issue

**Comment by leeway1208** [comment]
hi @tomerpetel  try the newest tag 2.0.3-beta2. Please let me know if there are still any issues. Thanks.

**Comment by tomerpetel** [comment]
@leeway1208 It's working on 2.0.3-beta2 :) when a prod release is planned?

**Comment by leeway1208** [comment]
ASAP 😄😄

**Comment by axelpart** [comment]
Hello @leeway1208. We recently upgraded using the latest version `2.0.4` and we also started seeing the the same warning. Same result observed as described on the initial comment, delegate is not called:

```
CocoaMQTT(warning): UNEXPECT SUBACK Recivied: SUBACK(id: 1)
CocoaMQTT(warning): UNEXPECT SUBACK Recivied: SUBACK(id: 2)
...
```
We tried to use array of topics and pass individual topics but the warning is still occurring.
