### ISSUE TITLE
module compiled with swift 5.1.3 cannot be imported by the swift 5.5.1 compiler

### ISSUE THREAD

**Issue by wjdwodud1130** [emqx/CocoaMQTT#422]
I use this Framework 2years ago Now i need to update Xcode & carthage.
But emqx/CocoaMQTT have a error (import CocoaMQTT) at MQTTManager.swift

And Carthage can`t updated and errors keep coming out

Xcode error content is module compiled with swift 5.1.3 cannot be imported by the swift 5.5.1 compiler

What can i do this error? 
I'd appreciate it if you could help me.

**Comment by leeway1208** [comment]
@wjdwodud1130  hi, I have already fixed it ,please try Carthage again.

**Comment by wjdwodud1130** [comment]
Thank you for your reply but what items should there be in the cartfile?

**Comment by leeway1208** [comment]
use `github "emqx/CocoaMQTT" "master"`
