### ISSUE TITLE
CocoaMQTT.swift line 2147483647 @objc CocoaMQTT.__ivar_destroyer

### ISSUE THREAD

**Issue by tunnaakshit** [emqx/CocoaMQTT#427]
App is crashing for iOS 15 and 14 version

crash logs: 
Crashed: com.apple.root.default-qos
0  libobjc.A.dylib                0x2430 objc_release + 16
1  CocoaMQTT                      0x70c0 @objc CocoaMQTT.__ivar_destroyer + 4429246656 (CocoaMQTT.swift:4429246656)
2  libobjc.A.dylib                0x6f10 object_cxxDestructFromClass(objc_object*, objc_class*) + 112
3  libobjc.A.dylib                0x3f08 objc_destructInstance + 88
4  libobjc.A.dylib                0xcdbc _objc_rootDealloc + 52
5  CocoaMQTT                      0x7068 CocoaMQTT.__deallocating_deinit + 251 (CocoaMQTT.swift:251)
6  CocoaMQTT                      0x7090 @objc CocoaMQTT.__deallocating_deinit + 4429246608 (<compiler-generated>:4429246608)
7  Dapp                           0x2bcc4 MqttService.initialiseClient() + 41 (MqttService.swift:41)
8  Dapp                           0x2badc closure #1 in MqttService.setupEnvironment() + 26 (MqttService.swift:26)
9  Dapp                           0x2da48 closure #2 in MqttService.getDevicePlatformConfig(completionBlock:) + 158 (MqttService.swift:158)
10 Dapp                           0x6f958 thunk for @escaping @callee_guaranteed () -> () + 4373936472 (<compiler-generated>:4373936472)
11 libdispatch.dylib              0x63194 _dispatch_call_block_and_release + 24
12 libdispatch.dylib              0x64198 _dispatch_client_callout + 16
13 libdispatch.dylib              0x3b3bc _dispatch_queue_override_invoke + 712
14 libdispatch.dylib              0x482e0 _dispatch_root_queue_drain + 328
15 libdispatch.dylib              0x48abc _dispatch_worker_thread2 + 160
16 libsystem_pthread.dylib        0x4e48 _pthread_wqthread + 224
17 libsystem_pthread.dylib        0x49f0 start_wqthread + 8

Kindly check 
Thanks

**Comment by leeway1208** [comment]
Hi ,Which tag version do you use?

**Comment by leeway1208** [comment]
Hi ,Which tag or release do you use?

**Comment by JaylinYu** [comment]
Could you provide us with more detailed information?
1. What action caused the crash.
2. Which version of CocoaMQTT are you using.

**Comment by tunnaakshit** [comment]
Hi
The crash happened during the initialisation of the client.
We were using version 1.1.3
Now we have upgraded it to version 2.0.2
Will check in the next release if the crash got resolved or not.

Thanks
Akshit Sharma

**Comment by leeway1208** [comment]
@tunnaakshit If you have the problem in the newest version, please let us know.😄😄

**Comment by tunnaakshit** [comment]
Will do, thanks!
