### ISSUE TITLE
UNEXPECT SUBACK 

### ISSUE THREAD

**Issue by sadeghgoo** [emqx/CocoaMQTT#435]
Hi after I subscribed to a topic I receive an error that prevent calling did subscribe delegate.

my CocoaMqtt version: 2.0.2
error: 
UNEXPECT SUBACK Recivied: id 3

**Comment by sadeghgoo** [comment]
![Screen Shot 2022-01-31 at 3 14 05 PM](https://user-images.githubusercontent.com/43542836/151788137-6cb77f8d-d183-457b-af50-39dac0073f02.png)

**Comment by jmjaimesmendoza** [comment]
Hi, I see you closed this yourself, did you solve it? how?

**Comment by jmjaimesmendoza** [comment]
> ![Screen Shot 2022-01-31 at 3 14 05 PM](https://user-images.githubusercontent.com/43542836/151788137-6cb77f8d-d183-457b-af50-39dac0073f02.png)

Hi, I see you closed this yourself, did you solve it? how? @sadeghgoo

**Comment by sadeghgoo** [comment]
Hi;
I updated CocoaMQTT and everything got fixed.
