### ISSUE TITLE
CocoaMQTT/WebSockets', '1.3.0-rc.2' is Index out of range

### ISSUE THREAD

**Issue by BeamCai** [emqx/CocoaMQTT#437]
pod 'CocoaMQTT/WebSockets', '1.3.0-rc.2'
system: 15.2.1 (19C63)
device：iPhone 12
<img width="1075" alt="企业微信截图_04ec52d5-07a3-4f49-93a4-af65ef9239f1" src="https://user-images.githubusercontent.com/84771984/152909629-2bdecddb-84dc-4755-a453-ff377d21e489.png">

**Comment by leeway1208** [comment]
Hi. Could you tell me what is the value of input in 'private func parse' function? thanks.

**Comment by BeamCai** [comment]
what's "private func parse" ? The problem we detected at Bugly was that it crashed while receiving callbacks. Can I have a private chat with you ？

**Comment by leeway1208** [comment]
@BeamCai Hi. Try to use the newest version. I just fixed the code.😄
