### ISSUE TITLE
Qos not respected on subscription

### ISSUE THREAD

**Issue by rafaelnobrekz** [emqx/CocoaMQTT#445]
Hi! Starting to know the library, I noticed that qos1 is hardcoded on MqttSubscription? Does this make sense ?
```
public func subscribe(_ topic: String, qos: CocoaMQTTQoS = .qos1) {
        let filter = MqttSubscription(topic: topic)
        return subscribe([filter])
    }
```

**Comment by leeway1208** [comment]
It's OK, It's swift syntax to set default values.

**Comment by rafaelnobrekz** [comment]
Hi, what I mean is the qos variable is not injected into MqttSubscription object thus what we set is completely ignored

**Comment by leeway1208** [comment]
haha. you are right. I will fix it.

**Comment by rafaelnobrekz** [comment]
Cool, thanks! I could have made a PR, but I thought maybe I was missing something 🤪
