### ISSUE TITLE
Connection to two mqtt 5.0 brokers fails

### ISSUE THREAD

**Issue by rafaelnobrekz** [emqx/CocoaMQTT#446]
Hello! Thanks for providing CocoaMQTT - I guess the only native Swift MQTT 5.0 client?
Trying to run the sample app against the brokers in https://test.mosquitto.org/ fail - I am able to connect but:
* Trying to subscribe to a topic yields an immediate disconnection
* Trying to publish to a topic crashes the library with the following:
<img width="1639" alt="Screen Shot 2022-03-24 at 16 34 15" src="https://user-images.githubusercontent.com/86966728/159996065-b48584b9-85e8-453f-bc02-fca9ce76e0fa.png">

I have also tried with a paho based 5.0 broker and the result is the same. The test broker `broker-cn.emqx.io` referenced in the sample works fine (apart from a "JSON" message prepending every message when version 5.0 is selected).

**Comment by rafaelnobrekz** [comment]
I can successfully connect/subscribe/publish on all three servers above from the MQTTX Mac client app
<img width="918" alt="Screen Shot 2022-03-24 at 17 13 40" src="https://user-images.githubusercontent.com/86966728/160002247-5023e2a1-00dd-4d84-959f-45ca7499aeb6.png">

**Comment by leeway1208** [comment]
hi, I will fix it later. I think it is a bug.😄

**Comment by rafaelnobrekz** [comment]
2.0.3-beta4 fixes the issue! 🎉
