### ISSUE TITLE
App crash because of UserDefaults key "version"

### ISSUE THREAD

**Issue by niralishaha25** [emqx/CocoaMQTT#450]
Since cocoaMQTT version 2.0.3 beta we are facing the crash in CocoaMQTT pod

we found that you are writing to the UserDefaults key "version", 
do note "version" is a very common key name and we are using it in our project.
so CocoaMQTT key is overriding content of "version" written by our project and vice versa.
If my application wipes "version" key, cocoaMQTT crashes for given below method
func queryMQTTVersion() -> String {
        return versionDefault.string(forKey: "version")!
    }

**Comment by leeway1208** [comment]
hi.I will update the key value.

**Comment by leeway1208** [comment]
If you still have the problem. Please let me know.

**Comment by niralishaha25** [comment]
Thanks for quick updated. I updated pod to 2.0.3 beta6 and could see the fix.
But can't see 2.0.3 beta6 in releases . The last release is 2.0.3 beta 4
Do let me know when the stable release would be available.

**Comment by leeway1208** [comment]
Hi. I have already released the version beta6.

**Comment by niralishaha25** [comment]
Thanks again

**Comment by rafaelnobrekz** [comment]
@leeway1208 older apps in the wild that have used the previous version of CocoaMQTT before this fix can experience a crash after this fix. Probably the lib should fallback to some sane default or try to read from the older key and use that as default if the existing value makes sense. I just got this after testing in a simulator instance that had the app previously with an older release:
<img width="1516" alt="Screen Shot 2022-04-28 at 12 22 43" src="https://user-images.githubusercontent.com/86966728/165788426-f753a293-654a-4fee-a8fd-c38712fb8646.png">
