### ISSUE TITLE
It's not an indication of a successful connection

### ISSUE THREAD

**Issue by WGFcode** [emqx/CocoaMQTT#451]
mqtt5.connect()

**Comment by leeway1208** [comment]
Hi . you can use delegate func mqtt5(_ mqtt5: CocoaMQTT5, didConnectAck ack: CocoaMQTTCONNACKReasonCode, connAckData: MqttDecodeConnAck) to know whether the connection is suceesful.

**Comment by WGFcode** [comment]
Thank you，Here's another question，In the swift5.6, an error will be reported when the closure replaces the proxy implementation method.
mqtt5?.didReceiveMessage = { (mq,code,ack) in
} 
error: Type of expression is ambiguous without more context

**Comment by leeway1208** [comment]
@WGFcode Thanks for report. I will review it ASAP.
