### ISSUE TITLE
Crash from FrameDisconnect, Index out of range

### ISSUE THREAD

**Issue by jimbengtsson92** [emqx/CocoaMQTT#452]
CocoaMQTT version: 2.0.2
iOS version: 15.4.0
Phone model: iPhone 13 Pro (Simulator)

After looking at the code (last image) it looks like checking that the array is not empty before getting the value from the array should do the trick.

![Screenshot 2022-04-25 at 13 42 02](https://user-images.githubusercontent.com/74904815/165082905-f061bce4-86a9-412a-9143-7e33b066d315.png)

![Screenshot 2022-04-25 at 13 42 18](https://user-images.githubusercontent.com/74904815/165082923-71c63b64-f445-4adf-946d-72bbeed48504.png)

![Screenshot 2022-04-25 at 13 49 21](https://user-images.githubusercontent.com/74904815/165083269-967bf435-c30a-46ce-9196-944bc08f64a9.png)

**Comment by leeway1208** [comment]
Hi . Thanks for the report. I will fix it right now.
