### ISSUE TITLE
Support of Swift Package Manager

### ISSUE THREAD

**Issue by phlpp77** [emqx/CocoaMQTT#459]
Hi there,
As stated in the readme file the swift package manager is not supported. I think the usage of cocoapods is laborious. Would it be possible to support the SPM?

Thanks.

Kind regards,
Philipp

**Comment by leeway1208** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/8113938/173719494-781f7aaf-86f6-488b-a0ec-d3aead41da58.png">
Hi, you can search the package like this. 😄
