### ISSUE TITLE
use mqtt5.0 properties,something seems wrong

### ISSUE THREAD

**Issue by 1989allen126** [emqx/CocoaMQTT#460]
when i set the under properties,mqtt communicate don`t work for me 
properties.correlationData = correlationData
properties.responseTopic = responseTopic
properties.userProperty = userProperty
i try to change something under the file
CocoaMQTT5Message.swift

 /// 3.1.3.2.7 Correlation Data
        if let willCorrelationData = self.willCorrelationData {
            let buff = UInt16(willCorrelationData.count).hlBytes + willCorrelationData
            properties += getMQTTPropertyData(type: CocoaMQTTPropertyName.correlationData.rawValue, value: buff)
        }
        
        /// 3.1.3.2.8 User Property
        if let willUserProperty = self.willUserProperty {
            willUserProperty.forEach { element in
                properties.append(UInt8(CocoaMQTTPropertyName.userProperty.rawValue))
                if isUTF8EncodedData {
                    let key = element.key.stringUTF8
                    properties += key .bytesWithLength
                    let value = element.value.stringUTF8
                    properties += value.bytesWithLength
                } else {
                    properties += element.key.bytesWithLength
                    properties += element.value.bytesWithLength
                }
            }
        }

others ，when decode publish message ，the application will crash，so i try to add code to avoid immediate use userProperty when the property was nil

File： MqttDecodePublish.swift
Function：in the function public func decodePublish(fixedHeader: UInt8, publishData: [UInt8])
//……
        //fixme:这里需要注意，直接强制解包会崩溃
        if userProperty == nil {
            userProperty = [:]
        }

        userProperty![key!] = value

**Comment by leeway1208** [comment]
Hi I find you committed the PR. I will review it and thanks for your support.😄
