### ISSUE TITLE
Compile error on iOS16 in CocoaMQTTTypes.swift

### ISSUE THREAD

**Issue by philippzagar** [emqx/CocoaMQTT#478]
When compiling this library on iOS16, I get the following compile error in the `CocoaMQTTTypes.swift` file: 
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/25406915/191319835-a2fa9461-3be5-4cd8-8590-d716b3671108.png">

Is this a known issue?

**Comment by leeway1208** [comment]
Hi. How about these. You can replace the code and have a try.
```
public enum CocoaMQTTError: Error {
    case invalidURL
    case readTimeout
    case writeTimeout
    if #available(OSX 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0, *) {
        public enum FoundationConnection : Error {
            case closed(URLSessionWebSocketTask.CloseCode)
        }
    }
}
```
