### ISSUE TITLE
No such module 'MqttCocoaAsyncSocket'

### ISSUE THREAD

**Issue by ravi-lirisoft** [emqx/CocoaMQTT#479]
Unable to build Example app using master branch or version 2.0.6

<img width="1141" alt="Screen Shot 2022-09-21 at 9 08 35 AM" src="https://user-images.githubusercontent.com/68231364/191409359-3640d82f-1400-49d6-8232-5ff408b4aeed.png">

Since we are in the integration phase, quick fix would be appreciated.

Thanks.

**Comment by leeway1208** [comment]
Hi. Trying to search ‘https://github.com/leeway1208/CocoaAsyncSocket’ and install it. Thanks.
<img width="1082" alt="install" src="https://user-images.githubusercontent.com/8113938/191410821-e1ebfbeb-55c1-46b6-84f7-e0ed9c8ce9d8.png">

**Comment by ksd** [comment]
I get the exact error. Rolling back to version 2.0.4 fixed this.

**Comment by ravi-lirisoft** [comment]
> I get the exact error. Rolling back to version 2.0.4 fixed this.

I did the same to resolve this issue.

But I also tried what @leeway1208 suggest to add the CocoaAsyncSocket additionally, didn't work.

**Comment by leeway1208** [comment]
Hi. I will fix it ASAP~~~

**Comment by ivaneChen** [comment]
HI
 I tried what @leeway1208 suggest to add the CocoaAsyncSocket additionally, didn't work too.

**Comment by leeway1208** [comment]
> HI I tried what @leeway1208 suggest to add the CocoaAsyncSocket additionally, didn't work too.

Hi. Please adding swift package as before, I have replaced the CocoaAsyncSocket library with MqttCocoaAsyncSocket.
