### ISSUE TITLE
Crash in CocoaMQTTStorage due to force unwrapping

### ISSUE THREAD

**Issue by FadyAckad** [emqx/CocoaMQTT#484]
### Platform
OSX

### Description
On macOS HighSierra, there's a bug in `UserDefaults` which causes it to lose its data and stop functioning until the machine is restarted or the process `cfprefsd` is forcibly killed. This causes a crash in `MQTTStorage` because of the following force unwrapping:
<img width="656" alt="Screenshot 2022-09-27 at 10 36 56" src="https://user-images.githubusercontent.com/18596351/192476955-b0ac97b6-6202-443b-b23a-45881ff3493e.png">

There is also a way to reproduce it on newer OSX version:
1. Run the app
2. Open the terminal and run the command `$ defaults delete your.app.bundle.id`

This also causes the app to crash immediately

**Comment by leeway1208** [comment]
Hi @FadyAckad How about providing a default value just like this?
<img width="731" alt="image" src="https://user-images.githubusercontent.com/8113938/192562774-37dae104-6cc8-4895-8a01-bd331ceb3fe3.png">
or do u have some good ideas? Thanks.

**Comment by FadyAckad** [comment]
Hello, Thank you for the quick reply. Sadly, we're still using version 3. So having it fallback to `3.1.1` would be best for us at the moment, but is it possible to avoid using `UserDefaults` here altogether and would having this flag as a property in the class work? From what I see the version is always set during the initialization of the client. So for example would the following snippet work?

```swift
private var mqttVersion: String = ""

func setMQTTVersion(_ version : String) {
    mqttVersion = version
}

func queryMQTTVersion() -> String {
    return mqttVersion
}
```

**Comment by leeway1208** [comment]
Hi. I write the default value for version which is 3.1.1 and also add static function to set version. Just using setMqtt3Version() or  setMqtt5Version().

**Comment by leeway1208** [comment]
Hi. I write the default value for version which is 3.1.1 and also add static function to set version. Please using setMqtt3Version() or setMqtt5Version(). Thanks.

**Comment by gestas-projects** [comment]
Hi, when this issue will be released?
