### ISSUE TITLE
can not connect to HiveMQ Cloud Broker, SSL, no Certificate 

### ISSUE THREAD

**Issue by joersv4** [emqx/CocoaMQTT#489]
Hello,

I have a problem with the connection to the HiveMQ Cloud Broker.

This code runs on my local mqtt broker (without SSL), but not on HiveMQ Cloud Broker (with SSL).
---------------------------
 ```
   var mqtt: CocoaMQTT5!
    
    func setUpMQTT() {
        let clientID = "CocoaMQTT-" + String(ProcessInfo().processIdentifier)
        mqtt = CocoaMQTT5(clientID: clientID, host: "xxxx.s1.eu.hivemq.cloud", port: 8883)
        mqtt.logLevel = .debug
        mqtt.username = "xxxx"
        mqtt.password = "xxxx"
        mqtt.willMessage = CocoaMQTT5Message(topic: "/will", string: "dieout")
        mqtt.keepAlive = 60
        mqtt.enableSSL = true
        mqtt.allowUntrustCACertificate = true
        mqtt.sslSettings = [kCFStreamSSLPeerName as String: "" as NSObject]
        
        mqtt.connect()
    }
```
---------------------------

I can not connect to the HiveMQ Cloud Broker.
I have tried everything, but nothing changed.

Wireshark of CocoaMQTT5
![Bildschirm­foto 2022-11-08 um 23 39 43](https://user-images.githubusercontent.com/63073440/200691512-57430aff-025b-4f37-8de1-abb375bae2be.png)

Wireshark of MQTTAnalyzer APP -> successful connection
![Bildschirm­foto 2022-11-08 um 23 43 37](https://user-images.githubusercontent.com/63073440/200691983-8e63ab54-633e-47c1-8c0c-a88d61557dfb.png)

So i see my app not send the "Client Key Exchange"

How can I fix this issue??

Thanks

**Comment by leeway1208** [comment]
Hi. Trying to set mqtt5!.sslSettings = [kCFStreamSSLPeerName as String: "xxxx.s1.eu.hivemq.cloud" as NSObject].

**Comment by joersv4** [comment]
Hi.

Thank you :)

now I have found the right parameters for connection to HiveMQ Cloud.

```
        mqtt.enableSSL = true
        mqtt.allowUntrustCACertificate = false
        mqtt.sslSettings = [kCFStreamSSLPeerName as String: "xxxx.s1.eu.hivemq.cloud" as NSObject]
```

its working well with "allowUntrustCACertificate = false"
