### ISSUE TITLE
RetainHandling attribute when subscribing

### ISSUE THREAD

**Issue by DDIsFriend** [emqx/CocoaMQTT#499]
When the RetainHandling attribute is set to sendOnSubscribe, the retain message cannot be received, and when it is set to none, the retain message can be received. The functions of these two attributes are just the opposite.

**Comment by leeway1208** [comment]
Thanks. Please have a try.

**Comment by leeway1208** [comment]
Thanks. Please try the newest commit.

**Comment by rafaelnobrekz** [comment]
@leeway1208 I've spent some hours trying to understand why my application doesn't work correctly with the latest version (that fixes some race conditions and user_property among other fixes

While this PR fixes the wrong binary values, the default value should now be set to `sendOnSubscribe` , not `none` ! As by default now a subscription doesn't get any retained messages
