### ISSUE TITLE
CocoaMQTTWill not always installed

### ISSUE THREAD

**Issue by clm57** [emqx/CocoaMQTT#502]
Trying to develop an App with MQTT.  Looking at code examples they use CocoaMQTTWill, which on my new app doesn't get included in the files when I do a pod  install.  When I do the pod install on the example code, it does get included.  So it would appear there is a setting in my Xcode project that causes CocoaMQTTWill not to be included.  Tried ios vs MacOs and it doesn't seem to do it.  

Can anyone tell me setting is likely to cause this?  

thanks in advance!

**Comment by leeway1208** [comment]
Hello . ‘CocoaMQTTWill’ has already updated to ’CocoaMQTTMessage‘ in the new version.

**Comment by clm57** [comment]
Thanks!
I still don't understand why I get different results when I do a fresh pod install for different projects, I get different source codes.  The CocoaMQTT checkout identifier was the same in both cases.  But knowing that the CocoaMQTTWill has been updated tells me I just need to move beyond that, so thank you!
