### ISSUE TITLE
Running error: EXC_BREAKPOINT

### ISSUE THREAD

**Issue by WGFcode** [emqx/CocoaMQTT#503]
# Xcode14.1, Running error
![WX20221201-172012@2x](https://user-images.githubusercontent.com/15343467/205015441-6d76fb74-470d-4ed8-9092-6043f474329d.png)

**Comment by leeway1208** [comment]
Hello, We test demo can run well on Xcode 14.1. Could you please provide more details.

**Comment by WGFcode** [comment]
> Reference



> Hello, We test demo can run well on Xcode 14.1. Could you please provide more details.
![2222222222](https://user-images.githubusercontent.com/15343467/205024691-1dd953ac-25ec-4303-a137-35e6a956f92f.png)
![111111111111](https://user-images.githubusercontent.com/15343467/205024719-60ef84f9-a9f8-4120-8b2c-89f7bfe9fa02.png)

**Comment by WGFcode** [comment]
> Hello, We test demo can run well on Xcode 14.1. Could you please provide more details.

![2222222222](https://user-images.githubusercontent.com/15343467/205025242-fc546e61-8aa4-479a-bbf9-bfeb98b9ce40.png)
![123](https://user-images.githubusercontent.com/15343467/205025365-6e746d35-3ca7-43e5-8757-409e0ae23bbb.png)

**Comment by leeway1208** [comment]
Hello. Pls go ahead to create PR for us If you have any solutions for this issue. Thanks much.

**Comment by WGFcode** [comment]
> Hello. Pls go ahead to create PR for us If you have any solutions for this issue. Thanks much.

I fixed the problem by updating the new version
