### ISSUE TITLE
Crash in  CocoaMQTTWebSocket

### ISSUE THREAD

**Issue by jimbengtsson92** [emqx/CocoaMQTT#512]
We have received 5 crashes from `CocoaMQTTWebSocket.swift - Line 193` which is the `timer?.cancel()` call inside here:
```
func reset() {
    timer?.cancel()
    timer = nil
}
```
All of these crashes come from v2.0.7 of CocoaMQTT. These are reported from crashlytics so the below stack trace is all info i have, I do not know of a way to reproduce it from our app.

![Screenshot 2023-01-19 at 12 10 38](https://user-images.githubusercontent.com/74904815/213428113-bd994ad9-7f0b-4a55-8515-73b2e7d93c83.png)

**Comment by leeway1208** [comment]
Hi. I will try to fix it.

**Comment by jimbengtsson92** [comment]
Hi,

Thank you for taking a time to look at the issue. I don't think the commit fixes the issue though. Please see my comment in the commit.

**Comment by przemyslaw-szurmak** [comment]
@jimbengtsson92 Hey, i have a feeling that my threading fix done in https://github.com/emqx/CocoaMQTT/pull/515 could help your case too.

**Comment by jimbengtsson92** [comment]
Thanks @przemyslaw-szurmak, I'll get back if the problem still occurs with this fix included.

**Comment by sky-NunoPereira** [comment]
Hi, @jimbengtsson92 were you able to reproduce the crash with this new fix? Or this crash stop occurring after the fix applied?
Thanks in advance.

**Comment by jimbengtsson92** [comment]
@sky-NunoPereira So far I have not seen any crashes from this package with this fix included. But it is worth noting that I have never been able to reproduce the crash myself, so I cannot say for sure that this has fixed it. But for now it looks promising at least.

**Comment by jimbengtsson92** [comment]
@sky-NunoPereira I think that the fix from @przemyslaw-szurmak fixed this issue. We have at least not received any more crashes after updating to the version with the fix included.

**Comment by przemyslaw-szurmak** [comment]
@jimbengtsson92 Thanks for letting is know!
