### ISSUE TITLE
How to set  subscription identifier when subcribe

### ISSUE THREAD

**Issue by SkylineJia** [emqx/CocoaMQTT#524]
How to set `subscriptionIdentifier` when use `mqtt5.subscribe`?

**Comment by leeway1208** [comment]
Hi. I will make an new interface to you.

**Comment by SkylineJia** [comment]
Subscribe to a topic with a subscription identifier. Then, the server closes the connection resulting in an error message "Remote peer has closed the socket". The error seems to stem from a four-byte issue in the code found at https://github.com/emqx/CocoaMQTT/blob/3fbf0e31827e3025cd7026e18ea83641a102333e/Source/FrameSubscribe.swift#L116  `subscriptionIdentifier.byteArrayLittleEndian`

According to the documentation found at https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901166, the subscription identifier should be a variable length byte.

**Comment by leeway1208** [comment]
Hello, could you provide PR to us? Thanks

**Comment by leeway1208** [comment]
Hello, I will fix it ASAP . Or could you provide PR to us and help us to fix this issue? Thanks~

**Comment by SkylineJia** [comment]
#525
