### ISSUE TITLE
MqttConnectProperties class properties: need help

### ISSUE THREAD

**Issue by ruijfcanas** [emqx/CocoaMQTT#526]
Hello community,

I'm having some trouble trying to understand what I should put in the parameters of `MqttConnectProperties`: `requestResponseInformation` and `requestProblemInfomation`.
I saw that both properties are `UInt8` but I've seen other tools use a boolean for this specific variables. Should I use `0x01` to enable the properties and `0x00` to disable them?

Thanks in advance!

**Comment by leeway1208** [comment]
I think you are right. There are some references. 
https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901053

**Comment by ruijfcanas** [comment]
Yap, looks like it. Going to save the page for future questions.
Thanks for the quick response!
