### ISSUE TITLE
pod 'CocoaMQTT/WebSockets' 报错

### ISSUE THREAD

**Issue by Aflysun** [emqx/CocoaMQTT#529]
pod 'CocoaMQTT' 就没问题
<img width="1450" alt="截屏2023-06-16 16 39 52" src="https://github.com/emqx/CocoaMQTT/assets/24726406/8441550e-241f-4f2d-a11f-71f97c27b607">

**Comment by Aflysun** [comment]
> <img alt="截屏2023-06-16 16 39 52" width="1450" src="https://user-images.githubusercontent.com/24726406/246365077-8441550e-241f-4f2d-a11f-71f97c27b607.png">

Xcode 版本 Version 14.3.1 (14E300c)

**Comment by Aflysun** [comment]
Xcode 版本 Version 14.3.1 (14E300c)

**Comment by leeway1208** [comment]
Hello, you can try angle-bracketed instead.

**Comment by Aflysun** [comment]
> Hello, you can try angle-bracketed instead.

Still not working
<img width="2097" alt="截屏2023-06-19 18 16 50" src="https://github.com/emqx/CocoaMQTT/assets/24726406/733a869f-1509-4f93-afc6-6777edf02739">
