### ISSUE TITLE
Data racing issue in CocoaMQTT5

### ISSUE THREAD

**Issue by dahuayuan** [emqx/CocoaMQTT#541]
<img width="1297" alt="Screenshot 2023-08-08 at 09 12 22" src="https://github.com/emqx/CocoaMQTT/assets/131290953/1477e063-8872-4722-a0e3-0723c1290abc">
The framework crashes from time to time as the picture shows above.

The reason is because `subscriptionsWaitingAck` is not thread safe. If there are many subscriptions happen simultaneously, the data racing issue will pop up. Please consider to make these variables thread safe. thanks

```

    /// The subscribed topics in current communication
    public var subscriptions: [String: CocoaMQTTQoS] = [:]

    fileprivate var subscriptionsWaitingAck: [UInt16: [MqttSubscription]] = [:]
    fileprivate var unsubscriptionsWaitingAck: [UInt16: [MqttSubscription]] = [:]
```

**Comment by dahuayuan** [comment]
If you enable "Thread sanitizer", you are able to see the data racing issue easily:
<img width="936" alt="Screenshot 2023-08-08 at 09 35 06" src="https://github.com/emqx/CocoaMQTT/assets/131290953/ace99dcd-9008-4681-b72b-a24251cf1d5d">
<img width="1333" alt="Screenshot 2023-08-08 at 09 32 59" src="https://github.com/emqx/CocoaMQTT/assets/131290953/8fa4316f-7336-460f-ae03-fed96dcc6377">

**Comment by zhihuitang** [comment]
It is fixed in [PR](https://github.com/emqx/CocoaMQTT/pull/543)
