### ISSUE TITLE
When recovering session, frame (FramePublish) topic is empty

### ISSUE THREAD

**Issue by ltAldoRaine** [emqx/CocoaMQTT#563]
Hello,

I have installed the 2.1.6 version via **Cocoapods**.

I'm facing very strange issue, it seems like, when opening and closing application very fast, some publish requests are saved in the **UserDefaults** and then **recoverSessionBy** method grabs those requests and publishes again, issue is when it's retrieving frames from the userdefaults, data decoding is not happening correctly, there is no value in the topic variable for mqtt version 5.0.

Please check screenshot below

**Comment by ltAldoRaine** [comment]
[https://ibb.co/PgFByqH](url)

**Comment by ltAldoRaine** [comment]
![Screenshot 2023-10-31 at 10 38 18](https://github.com/emqx/CocoaMQTT/assets/17614392/5f32da85-0ab0-443b-a2c0-a3a144e5734a)

**Comment by JaylinYu** [comment]
NULL topic publish is a malformed msg

**Comment by ltAldoRaine** [comment]
@JaylinYu Yes, I know. Cocomqtt is sending message with empty topic

**Comment by leeway1208** [comment]
Please try to make `mqtt!.cleanSession = false`

**Comment by JaylinYu** [comment]
Could u kind check if this is fixed by commit ff7c07b
