### ISSUE TITLE
Not able to connect hivemq.cloud TLS/SSL port(8883).

### ISSUE THREAD

**Issue by snr-lab** [emqx/CocoaMQTT#565]
I am getting following error while trying to connect to hivemq.cloud TLS/SSL port(8883).

2023-11-04 23:02:33.126929+0530 Dev[7442:858287] [connection] nw_connection_copy_connected_path_block_invoke [C6] Client called nw_connection_copy_connected_path on unconnected nw_connection
2023-11-04 23:02:33.127087+0530 Dev[7442:858287] [] tcp_connection_is_cellular No connected path

Error Domain=MGCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}

However I am able to connect to the same broker from Android (Paho JAVA library)

Please help me to fix this issue.

Let me know if any other information is required.

**Comment by leeway1208** [comment]
Please provide us with your demo.

**Comment by snr-lab** [comment]
[CocoaMQTT.zip](https://github.com/emqx/CocoaMQTT/files/13281864/CocoaMQTT.zip)

I have attached a demo application (MQTT v3.1.1) to reproduce the issue
To verify if the credentials are correct you can use this Android app to test.

https://play.google.com/store/apps/details?id=snr.lab.iotmqttpanel.prod

**Comment by leeway1208** [comment]
[CocoaMQTT_reply.zip](https://github.com/emqx/CocoaMQTT/files/13293207/CocoaMQTT_reply.zip)
Hello. Please refer to this demo .

**Comment by snr-lab** [comment]
Thanks @leeway1208 

The application is working now.

**Comment by dilnuryuldashev** [comment]
@leeway1208 I know that this is an old thread, but I am encountering the same issue. I downloaded your project, but I got the same exact error. Only the 3.1.1 version is working without giving out an error, but even then, it is immediately disconnected. I wonder if you know what's going on. 

`[TRACE] [didConnectAck]: ack: notAuthorized
[TRACE] [didDisconnect]: Error Domain=MGCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}
[TRACE] [didStateChangeTo]: new state: disconnected
[TRACE] [didStateChangeTo]: new state: disconnected
tabbar index: 2
tabbar index: 0
[TRACE] [didStateChangeTo]: new state: connecting
nw_connection_copy_connected_path_block_invoke [C2] Client called nw_connection_copy_connected_path on unconnected nw_connection
tcp_connection_is_cellular No connected path
[TRACE] [didConnectAck]: ack: notAuthorized
[TRACE] [didStateChangeTo]: new state: disconnected
[TRACE] [didDisconnect]: Error Domain=MGCDAsyncSocketErrorDomain Code=7 "Socket closed by remote peer" UserInfo={NSLocalizedDescription=Socket closed by remote peer}
[TRACE] [didStateChangeTo]: new state: disconnected`
